### PR TITLE
Upgrade ItchySats app to `0.4.0`

### PR DESCRIPTION
**Pull request by scratchscratchscratchy**
0.4.0 includes:
- Perpetual CFDs that are extended every hour.
- Some connection stability improvements.
- Some minor user interface improvements
- Internal model changes that require a hard reset of the CFD database. This is a breaking change.

Updated screenshots that reflect the interface changes:

1.
Screen Shot 2022-02-02 at 9 24 21 pm

2.
Screen Shot 2022-02-02 at 9 24 28 pm

3.
Screen Shot 2022-02-02 at 9 25 12 pm

### CODE REVIEW

**Comment by lukechilds** [comment]
When you say "This is a breaking change." do you mean the change is automatically handled by ItchySats or some manual steps are required by users?

**Comment by scratchscratchscratchy** [comment]
> When you say "This is a breaking change." do you mean the change is automatically handled by ItchySats or some manual steps are required by users to upgrade?

It is automatically handled, no manual steps required. The only sad part is, that we lose the history of previous CFDs. The internal model change was so big that we were unable to migrate. In the future we are planning to always migrate the database.

The old version does not create offers anymore and we are closing all currently remaining positions to be closed using the oracle attestation. 
The new maker runs on a different port (we just updated that on the PR). Eventually we might change the old maker to run on an incompatible version so the users see a warning that they should upgrade (but they can't create new positions against the old version anyway).

**Comment by lukechilds** [comment]
Got it, thanks for the explanation!

**Comment by lukechilds** [comment]
Tested and working great, got a perpetual position open! 🚀

**Comment by mayankchhabra** [comment]
Solid update! We [updated](https://github.com/getumbrel/umbrel-apps-gallery/commit/78fccd23840581f0f657cad3a2a2c12879170828) the gallery images with your latest screenshots 

The app icon and gallery images are directly fetched from [getumbrel/umbrel-apps-gallery](https://github.com/getumbrel/umbrel-apps-gallery) so if you ever want to tweak or update them, feel free directly open a PR on that repository. (Oh and if you need the Figma file just hit me up, cheers!)

**Pull request merged**
