### PR TITLE
Pass LND IP to Tor so it can proxy connections

### LINKED ISSUE #55: Unable to connect to LND / Bitcoin tor
Try the following hosts (mainnet)

```
024800ef3df70dc53bd2182dbe913a7abf8c0cb655fcc6ac494dfd250c0b74244f@n3k54z5gwxsv3nndkqwhhkcsyqilv6vrpqo4e3lzq6pkqb65xj3txjad.onion:9735

027cf9967a2d79631c665417b363d7113764bdede6c7bc21897062655448cd3581@flh6m6hd4wg4o2e5bfdelg4cobvsmcp5cxftaujsvwou5wg5iuwe5wad.onion:9735
```

Just use ```nc -x localhost:9050 onionname 9735``` to test the connections, and they seem to fail

I guess if this doesn't work we might have to revert back to host networking.

# Reproducing Information

## LND

1. Install and configure docker-compose framework
2. Remove all the other services in docker-compose.yml so we just sync up lnd (and tor obviously)
3. Try to connect to the LND from another server

## Bitcoind

1. Install and configure docker-compose framework
2. Remove all services except for bitcoind and tor
3. Grab the tor host ```docker exec -it bitcoin bitcoin-cli getnetworkinfo```
4. Try to connect to the tor host using ```nc -x localhost:9050 -vz onionaddress port``` on another host

### PR DESCRIPTION
**Pull request by lukechilds**
Resolves #55

### CODE REVIEW

**Comment by nolim1t** [comment]
cool testing this

**Comment by nolim1t** [comment]
might need to do something for bitcoind too

**Comment by nolim1t** [comment]
LND part is working

**Comment by mayankchhabra** [comment]
LGTM! Awesome speed ⚡️

**Pull request merged**
