### PR TITLE
Bump lnd version

### PR DESCRIPTION
**Pull request by nolim1t**
Bump LND version to ```lncm/lnd:v0.10.4-experimental```

### CODE REVIEW

**Comment by mayankchhabra** [comment]
Would be great if we can shift to standard "non-experimental" lnd images. How important in your opinion is `routing.assumechanvalid=1`?

**Comment by nolim1t** [comment]
Better UX..

**Comment by mayankchhabra** [comment]
How, can you explain? Genuinely want to understand what it does.

**Comment by nolim1t** [comment]
speeds up transactions for nearby peers

**Pull request merged**
