### PR TITLE
Use the latest build of bitcoind

### PR DESCRIPTION
**Pull request by AaronDewes**
No changes were made, but the dource code has been verified in a more secure way.

### CODE REVIEW

**Review by nolim1t — APPROVED** [review]

**Comment by lukechilds** [comment]
Aren't the LNCM builds supposed to be deterministic? The hash shouldn't have changed on the image if it was built from the same source but just verified differently.

**Comment by nolim1t** [comment]
Yes it is but this uses the old way of fetching and verifying both sources from different sites.

We had to rely on workarounds of using the same site.

**Comment by lukechilds** [comment]
But this resulting image has a different hash?

If the verification method has changed but the resulting image is the same the hash should not have changed.

**Comment by nolim1t** [comment]
According to docker its a new build irespective of changes. The way the docker images works if you run the release scripts it will be a new build number and it will get reassigned. This is so you can still refer to the old ones.

**Comment by lukechilds** [comment]
The Docker images don't include tags, if the hash has changed the image is different, so either the builds aren't deterministic, or someone is potentially trying to sneak something in.

**Comment by lukechilds** [comment]
The builds are not deterministic, the `bitcoind` user entry in `/etc/shadow` changes between builds.

```
$ container-diff diff daemon://bitcoind:old daemon://bitcoind:new --type=file

-----File-----

These entries have been added to bitcoind:old: None

These entries have been deleted from bitcoind:old: None

These entries have been changed between bitcoind:old and bitcoind:new:
FILE               SIZE1        SIZE2
/etc/shadow        452B         452B


$ container-diff diff daemon://bitcoind:old daemon://bitcoind:new --type=file --filename=/etc/shadow

-----File-----

These entries have been added to bitcoind:old: None

These entries have been deleted from bitcoind:old: None

These entries have been changed between bitcoind:old and bitcoind:new:
FILE               SIZE1        SIZE2
/etc/shadow        452B         452B


-----Diff of /etc/shadow-----


--- bitcoind:old
+++ bitcoind:new
@@ -28 +28 @@
-bitcoind:!:18749:0:99999:7:::
+bitcoind:!:18764:0:99999:7:::
```

**Comment by lukechilds** [comment]
I'll close this since there's no need to push this out to users. It'll mean everyone will have to download a new bitcoind image during OTA that's identical to the one they already have apart from the `/etc/shadow` entry.

**Pull request closed without merging**
