### PR TITLE
feat: add I2P

### PR DESCRIPTION
**Pull request by count-null**
First step towards fixing #694, #810, #1476

[Raspiblitz PR to add I2P](https://github.com/rootzoll/raspiblitz/pull/3330)

Adds i2pd docker image to core services. 
Next step is to modify bitcoin.conf to use the I2P proxy/router [as described in bitcoin-core](https://github.com/bitcoin/bitcoin/blob/master/doc/i2p.md)

By default, i2pd will operate as a router and passively transmit data from peers on the network. This could be a bandwidth issue for some users. 

[i2pd configuration](https://i2pd.readthedocs.io/en/latest/user-guide/configuration/) has options to limit bandwidth or disable transit. 

In the [i2pd Dockerfile](https://github.com/PurpleI2P/i2pd/blob/openssl/contrib/docker/Dockerfile#L14), configuration is hard coded as cli options. 

A PR is necessary in the i2pd repo to enable using a non-default configuration set. More in [this issue](https://github.com/PurpleI2P/i2pd/issues/1788)

### CODE REVIEW

**Comment by awholegnuworld** [comment]
Amazing! i2p for the win!

**Comment by awholegnuworld** [comment]
If this is added, would transmission also be able to connect over I2p? I can image this being useful for privacy in torrenting.

**Comment by count-null** [comment]
> If this is added, would Transmission also be able to connect over I2p? I can image this being useful for privacy in torrenting.

It doesn't appear Transmission supports alternate data layers. May be possible with i2pd proxies. https://github.com/majestrate/XD is a torrent client which is i2p only. This would be a conversation for umbrel-apps repo tho. This PR only adds the I2P daemon to umbrel.

**Comment by awholegnuworld** [comment]
Will the WebGui of I2p be open? It has lots of built in management features, and a torrent client.

**Comment by count-null** [comment]
@awholegnuworld 
> Will the WebGui of I2p be open? It has lots of built in management features, and a torrent client.

This PR uses the lightweight i2pd implementation. The "official" implementation written in Java and includes a torrent client and management tools. The Java version is over 100MB and the lightweight i2pd (C++) binary is ~1MB.

Assuming i2p will be a core service, it should have a small footprint with functionality added in additional apps. 
[XD](https://github.com/majestrate/XD) has webUI and uses the SAM proxy (the same interface as bitcoin-core) so it should be a fine candidate for the app store once i2p is in umbrel. 

i2pd gets configured from file or command line args. There could be an umbrel setting for things like setting bandwidth limits, etc.

**Comment by awholegnuworld** [comment]
Ah, neat! I've never used the lightweight client before! I knew of its existence, I just never tried it.

**Comment by nevets963** [comment]
@count-null Many thanks for the PR!

Before Christmas, we updated the Bitcoin app to include the ability to use I2P. More details here: https://twitter.com/umbrel/status/1605906942555148288

With the above update - is it safe to now close this PR?

**Comment by count-null** [comment]
Excellent work Umbrel team 👍

**Pull request closed without merging**
