### PR TITLE
Add in watchtower support so we can utilize it later

### PR DESCRIPTION
**Pull request by nolim1t**
Add in watchtower support so we can utilize it later in having each node watch out for each other and have a secure network (see [watchtower notes](https://github.com/lightningnetwork/lnd/blob/master/docs/watchtower.md))

### CODE REVIEW

**Comment by mayankchhabra** [comment]
Good line of thought, @nolim1t. Having Umbrel users added to each other's Watchtowers would be cool, but here's why I don't think it's a good idea right now:

- This PR enables watchtower server and client, but none of them will actually be used because no clients are added to the any of the watchtower servers. 

- PRs should add features in full. Unimplemented features can make the codebase confusing and harder to maintain. 

- We do not specifically need to enable watchtower right now. They can be enabled later via an OTA update once they're implemented in full.

- The [task-list for Umbrel Public Beta](https://github.com/orgs/getumbrel/projects/1) is already too tight and it'd be great to finish those tasks first, else we can end up delaying our launch.

- Long term tasks like this one should be added to the [medium/long-term idea board](https://github.com/orgs/getumbrel/projects/2) first, so we can brainstorm on them when the time comes and plan their implementation.

**Comment by nolim1t** [comment]
Its complete from this repos point of view. It enables it for later and allows people to enable it from the command line.

For the users to access it through the UI, it has to be done separately as a middleware and dashboard task.

This is the first step

**Comment by mayankchhabra** [comment]
I understand the PoV, but if people still have to update `lnd.conf` from the command line to use watchtowers, they can themselves enable the watchtowers too.

**Comment by nolim1t** [comment]
I'm just laying the groundwork all ready. It doesn't impact anything

**Comment by nolim1t** [comment]
Part of #212

**Comment by mayankchhabra** [comment]
Closing this due to inactivity.

**Pull request closed without merging**
