### PR TITLE
App Submission: Agora

### PR DESCRIPTION
**Pull request by yzernik**
# App Submission

### App name
Agora

### Version
0.1.2

### One line description of the app
File server that accepts Lightning Network payments for downloads

### Summary of the app
Agora is a project that allows anyone to sell files on the web for bitcoin using the Lightning Network.

Agora serves the contents of a local directory, providing file listings and downloads over HTTP. For example, you can point it at a directory full of PDFs, allowing users to browse and view the PDFs in their web browser. If agora is connected to an [LND](https://github.com/lightningnetwork/lnd) node, it can be configured to require [Lightning Network](https://en.wikipedia.org/wiki/Lightning_Network) payments for downloads.

### Developer name
Casey Rodarmor and Sönke Hahn

### Developer website
https://agora-org.github.io/agora/

### Source code link
https://github.com/agora-org/agora

### Support link
https://t.me/agoradiscussion

### Requires
- [ ] Bitcoin Core
- [ ] Electrum server
- [x] LND

### 256x256 SVG icon
SVG link: https://github.com/agora-org/agora/blob/master/logo.svg

### Gallery images
Screenshot from 2022-03-27 19-09-57
Screenshot from 2022-03-27 19-10-53
Screenshot from 2022-03-27 18-45-09

### I have tested my app on:
- [ ] [Umbrel dev environment](https://github.com/getumbrel/umbrel-dev)
- [x] [Umbrel OS on a Raspberry Pi 4](https://github.com/getumbrel/umbrel-os)
- [ ] [Custom Umbrel install on Linux](https://github.com/getumbrel/umbrel#-installation)

### CODE REVIEW

**Comment by lukechilds** [comment]
Thanks for working on packaging this @yzernik, Agora is such a cool idea.

Do you know if there are any plans to add a web UI for uploading files and configuring the payment settings?

In it's current state requiring users to scp over files and then manually create `.agora.yaml` via CLI it's probably not going to be usable by the vast majority of Umbrel users who aren't famialir with the command line.

**Comment by yzernik** [comment]
Thanks @lukechilds !

I just added `filebrowser` container to the docker-compose, so now there's a user-friendly way to manage files.
It's not technically part of the Agora app, but I think it should work.

So now there are two containers:
1) The public-facing Agora app that anyone can access on port 12080 to download and pay for files.
2) The `filebrowser` app that can only be accessed with `APP_PASSWORD` to upload/manage files.

**Comment by lukechilds** [comment]
Wow thanks for getting on this so quickly @yzernik!

I think this could still be a little confusing for users since there are two completely seperate apps running on different ports.

Maybe just a simple static web page as the default could be helpful that explains how to use Agora. e.g that files uploaded via the file manager URL will be served via the Agora URL and that a config file is needed to charge for the downloads.

Would also maybe simplify things a bit if there was an NGINX proxy running infront of this and serving everything from a single port. so e.g `/admin` is the static "home" page that users end up on if they click the app icon from Umbrel. `/admin/files` is the files directory, and `/` just goes direct to Agora. Or something to that effect.

What do you think?

**Comment by yzernik** [comment]
Sounds good @lukechilds.

I set up the nginx routes as you described, and I think it works.

The static landing page at `http://umbrel.local:12080/admin/` is just a plain html file. I might try to add some CSS later.

**Review by lukechilds — APPROVED** [review]

**Comment by lukechilds** [comment]
Nicely done! Excellent work on this @yzernik, thanks so much!

**Comment by mayankchhabra** [comment]
Congrats on the [launch](https://twitter.com/getumbrel/status/1511316135316439043), @yzernik! 🚀

Really nice work on packaging Agora. [Here](https://github.com/getumbrel/umbrel-apps-gallery/tree/master/agora) are the gallery images and app icon. If you ever want to change/update them, feel free to directly open a PR at [getumbrel/umbrel-apps-gallery](https://github.com/getumbrel/umbrel-apps-gallery). Keep up the amazing work!

**Comment by Ahmed262111** [comment]
> # App Submission
> ### App name
> Agora
> 
> ### Version
> 0.1.2
> 
> ### One line description of the app
> File server that accepts Lightning Network payments for downloads
> 
> ### Summary of the app
> Agora is a project that allows anyone to sell files on the web for bitcoin using the Lightning Network.
> 
> Agora serves the contents of a local directory, providing file listings and downloads over HTTP. For example, you can point it at a directory full of PDFs, allowing users to browse and view the PDFs in their web browser. If agora is connected to an [LND](https://github.com/lightningnetwork/lnd) node, it can be configured to require [Lightning Network](https://en.wikipedia.org/wiki/Lightning_Network) payments for downloads.
> 
> ### Developer name
> Casey Rodarmor and Sönke Hahn
> 
> ### Developer website
> https://agora-org.github.io/agora/
> 
> ### Source code link
> https://github.com/agora-org/agora
> 
> ### Support link
> https://t.me/agoradiscussion
> 
> ### Requires
> * [ ]  Bitcoin Core
> * [ ]  Electrum server
> * [x]  LND
> 
> ### 256x256 SVG icon
> SVG link: https://github.com/agora-org/agora/blob/master/logo.svg
> 
> ### Gallery images
> Screenshot from 2022-03-27 19-09-57 Screenshot from 2022-03-27 19-10-53 Screenshot from 2022-03-27 18-45-09
> 
> ### I have tested my app on:
> * [ ]  [Umbrel dev environment](https://github.com/getumbrel/umbrel-dev)
> * [x]  [Umbrel OS on a Raspberry Pi 4](https://github.com/getumbrel/umbrel-os)
> * [ ]  [Custom Umbrel install on Linux](https://github.com/getumbrel/umbrel#-installation)

**Comment by amtexugo** [comment]
have a tutorial to config this instalation? TKS

**Pull request merged**
