### PR TITLE
App submission: usocial.

### PR DESCRIPTION
**Pull request by ibz**
# App Submission

### App name

usocial

### Version

v0.1.1

### One line description of the app

Read. Listen. Pay back.

### Summary of the app

The podcast client and feed reader for your personal server. With Lightning Network support.

* **Simple** interface (minimalist HN-like design)
* **Optionally** multi-user
* **Decentralized** karma
* **Clean** code (Python / Flask / SQLite)
* Search podcasts from Podcast Index
* Support for the Podcasting 2.0 `value` tag, sending Bitcoin payments to podcast creators over the Lightning Network

### Developer name

Ioan Bizău

### Developer website

http://usocial.me

### Source code link

https://github.com/ibz/usocial

### Support link

https://github.com/ibz/usocial/issues

### Requires
- [x] Bitcoin Core
- [ ] Electrum server
- [x] LND

### 256x256 SVG icon

https://raw.githubusercontent.com/ibz/usocial/master/usocial/static/mu.svg

### Gallery images

Screenshot from 2022-02-05 00-08-30
Screenshot from 2022-02-05 00-09-30
Screenshot from 2022-02-05 00-11-10

### I have tested my app on:
- [ ] [Umbrel dev environment](https://github.com/getumbrel/umbrel-dev)
- [x] [Umbrel OS on a Raspberry Pi 4](https://github.com/getumbrel/umbrel-os)
- [ ] [Custom Umbrel install on Linux](https://github.com/getumbrel/umbrel#-installation)

### CODE REVIEW

**Review by lukechilds — CHANGES_REQUESTED** [review]
Daaamn bro you're on fire, another app already!

You need to commit `data/.gitkeep` so the data dir gets created with the correct permissions. Otherwise it'll be created as root and the app will fail to start with a fs permission error.

After doing that the app runs for me fine, however clicking a podcast doesn't play it and I see this in dev console:

Screenshot 2022-02-08 at 17 51 46

Any ideas?

**Comment by ibz** [comment]
Wow, very strange. Can you tell me what browser / OS you are on @lukechilds ?

**Comment by ibz** [comment]
Yeah, I think that can only happen if you add a podcast as a "blog" rather than as a "podcast", which I thought nobody would ever do. But hey, you are my first real user... ! I'll prepare an update. Thanks!

**Comment by lukechilds** [comment]
Lol.

I'm pretty sure what I did was:
- Click add podcast
- Search "Bitcoin"
- Click the eye icon next to "Tales from the Crypt"
- Go back to the main view and click on a podcast.

Not 100% sure though, I may have clicked something else while I was poking around.

**Comment by ibz** [comment]
Closing this since I messed up my repo (submitted this from master rather than from a feature branch, while also submitting updates for Lightning Shell in the same time).

Will re-open, but I figured it's a good idea to add DB migrations as well at this point!

**Comment by ibz** [comment]
> I'm pretty sure what I did was:

You are right, I found the bug. You tried to play while looking at "All", not at the TFTC feed itself. Anyway, fix is on the way...

**Pull request closed without merging**
