### PR TITLE
Route BTC Price API request via manager on Tor

### LINKED ISSUE #248: Route BTC Price API request via manager on Tor
Currently, the price is being fetched on the client-side. We should have it routed via Tor on the backend and returned by the manager.

### PR DESCRIPTION
**Pull request by louneskmt**
These 3 PR resolve #248 

Adds Tor environment variables for manager container.

Related:
- https://github.com/getumbrel/umbrel-manager/pull/53
- https://github.com/getumbrel/umbrel-dashboard/pull/235

### CODE REVIEW

**Review by mayankchhabra — DISMISSED** [review]
Great work on all the 3 PRs, Lounès! This is exactly how we'd have implemented. Thanks so much! :)

**Comment by lukechilds** [comment]
This is looking great @louneskmt!

I see you've added the Docker Hub credentials as mentioned in https://github.com/getumbrel/umbrel-manager/pull/53#issuecomment-703242299.

The method me and @mayankchhabra have been using for development is for the getumbrel/umbrel PR to include the links to your dev images. So if you update this PR to point to your images in the Compose file (`louneskmt/manager:master` etc) then me and @mayankchhabra can really easily test this out by running:

```
sudo scripts/update/update --repo louneskmt/umbrel#master
```

Also best to avoid submitting PRs from your master branch for this reason too. But fine for now while you only have a single PR open.

**Comment by louneskmt** [comment]
Thanks for the tip! 

> Also best to avoid submitting PRs from your master branch for this reason too. But fine for now while you only have a single PR open.

Yes, I created a new branch this morning for #267 ([here](https://github.com/louneskmt/umbrel-dashboard/tree/custom-amount-invoice)).

**Comment by lukechilds** [comment]
Awesome work @louneskmt and really clean high quality code, love it!

I've merged your manager and dashboard PRs and published new images, can you update this PR to the latest version of the official images and then it's good to be merged.

Latest releases are:
https://github.com/getumbrel/umbrel-manager/releases/tag/v0.2.7
https://github.com/getumbrel/umbrel-dashboard/releases/tag/v0.3.10

**Review by mayankchhabra — APPROVED** [review]

**Review by lukechilds — APPROVED** [review]

**Pull request merged**
