### PR TITLE
Update Jam to `v0.0.6`

### PR DESCRIPTION
**Pull request by theborakompanioni**
This version includes:
- joinmarket-webui: [v0.0.6](https://github.com/joinmarket-webui/joinmarket-webui/releases/tag/v0.0.6)
- joinmarket-clientserver: [v0.9.6](https://github.com/JoinMarket-Org/joinmarket-clientserver/releases/tag/v0.9.6)

All notable changes of the UI can be seen in the [Jam v0.0.6 changelog](https://github.com/joinmarket-webui/joinmarket-webui/blob/v0.0.6/CHANGELOG.md)

Updates to the image:
- increase api request timeout from 60sec to 5min [#34](https://github.com/joinmarket-webui/joinmarket-webui-docker/pull/34)
- update to default config for v0.9.6 [#32](https://github.com/joinmarket-webui/joinmarket-webui-docker/pull/32)

### CODE REVIEW

**Review by dnlggr — APPROVED** [review]
LGTM! ✅

**Comment by dnlggr** [comment]
Hey @lukechilds, congrats on the big v0.5.0 release. Exciting stuff! 

Should I move this PR over to the new [umbrel-apps](https://github.com/getumbrel/umbrel-apps) repository?

**Comment by mayankchhabra** [comment]
Thanks @theborakompanioni and @dnlggr!

You're right. We've moved the app store to its own, dedicated repository: [getumbrel/umbrel-apps](https://github.com/getumbrel/umbrel-apps). The primary benefit being that new app releases + app updates are pushed immediately to all Umbrel users as soon as PRs are merged, instead of being bundled with Umbrel releases. 

So yes, please feel free to open this PR on that repo. :)

The submission guidelines and framework are more or less same, with the noted addition of a new manifest file to contain all the app store listing data and such (we've already migrated Jam to it). The up-to-date instructions can be found in the repo's [README](https://github.com/getumbrel/umbrel-apps/blob/master/README.md). If you have any questions, let us know and we'll be more than happy to help.

Cheers!

**Comment by theborakompanioni** [comment]
> So yes, please feel free to open this PR on that repo. :)

Nice. Thank you. Closing this in favor of https://github.com/getumbrel/umbrel-apps/pull/23.

**Pull request closed without merging**
