### PR TITLE
usocial v0.1.6

### PR DESCRIPTION
**Pull request by ibz**
Changes: https://usocial.me/history/#v0.1.6

Thank you!

### CODE REVIEW

**Comment by louneskmt** [comment]
Hey, thanks for this PR!

Ongoing testing:
- [x] Checksums are correct and are for a multiarch manifest
- [x] Registry has been updated
- [ ] Update working on arm64
- [ ] Update working on amd64

**Comment by louneskmt** [comment]
Looks like the images crashes on start:
image

Any idea?

**Comment by louneskmt** [comment]
I'm testing the update on testnet, maybe that's where the issue comes from.

**Comment by ibz** [comment]
Hey @louneskmt thanks so much for testing!

Are you really testing an upgrade or a fresh install of the app? I mean, did you have the app installed and then updated Umbrel or did you update Umbrel and then install the app from scratch?

**Comment by louneskmt** [comment]
It's a fresh install on a brand new Testnet instance (but synced 100%).

**Comment by ibz** [comment]
I'll close this for now. Planning to move from SQLite to PostgreSQL anyway, so I will send another update later.

**Pull request closed without merging**
