### PR TITLE
Add AutoSats app

### PR DESCRIPTION
**Pull request by bezysoftware**
# App Submission

### App name
AutoSats

### Version
0.10.0

### One line description of the app
Easiest non-custodial way to accumulate bitcoin

### Summary of the app
AutoSats is the easiest non-custudial DCA solution you can run on your own node. It lets you periodically buy bitcoin on exchanges according to your defined schedule and automatically withdraw it to your own wallet once it hits a specified threshold. 

### Developer name
bezysoftware

### Developer website
https://github.com/bezysoftware/autosats

### Source code link
https://github.com/bezysoftware/autosats

### Support link
https://github.com/bezysoftware/autosats/issues

### Requires
- [ ] Bitcoin Core
- [ ] Electrum server
- [x] LND

### 256x256 SVG icon
https://github.com/bezysoftware/autosats/blob/main/Assets/Logo.svg

### Gallery images
_(Upload 3 to 5 high-quality gallery images (1440x900px) of your app in PNG format, or just upload 3 to 5 screenshots of your app and we'll help you design the gallery images.)_

obrazek
obrazek
Screenshot2
Screenshot3

### I have tested my app on:
- [ ] [Umbrel dev environment](https://github.com/getumbrel/umbrel-dev)
- [x] [Umbrel OS on a Raspberry Pi 4](https://github.com/getumbrel/umbrel-os)
- [ ] [Custom Umbrel install on Linux](https://github.com/getumbrel/umbrel#-installation)

Resolves https://github.com/bezysoftware/autosats/issues/9

### CODE REVIEW

**Comment by louneskmt** [comment]
Hey, thanks for this PR! 

Just for you to know, Umbrel uses the LND integrated wallet, and not the Bitcoin Core one (I'm seeing that you're using this last for AutoSats).

**Comment by louneskmt** [comment]
> Does that mean balance which is sent to the core wallet isn't visible thru lnd?

Yes, they are two different Wallet and Umbrel doesn't use or display the Core one. 

> Would I in that case need to interface with lnd instead and use it's grpc endpoints to generate a new withdrawal address?

Yes exactly. You could add a WALLET_BACKEND env var to allow the user to choose which wallet to use (I mean for the general AutoSats user, not Umbrel user). Then we can configure the AutoSats Umbrel app to use LND as Wallet backend.

**Comment by lukechilds** [comment]
Sorry I'm just a little bit behind, will review as soon as I'm able, thanks for your patience!

**Comment by bezysoftware** [comment]
No worries, I read your blog post about the seed funding, I can imagine that taking a lot of your time. Congratz btw! Umbrel is a big inspiration in this regard

**Comment by lukechilds** [comment]
Thanks @bezysoftware 💜

**Comment by lukechilds** [comment]
Hey @bezysoftware, thanks so much for this. AutoSats looks seriously cool! 🔥

Just wanted to say after a quick review, I don't think Umbrel is in a state where it's quite ready for your app yet. There recently were a small number of reports of Umbrel users who lost funds, and while it isn't totally clear exactly how it happened, it seems like it was caused by the Tor hidden service for some apps being leaked.

We have ideas for how we can add protections at the Umbrel layer to protect all apps against these kinds of attacks, however we haven't implemented them yet during beta. We are currently working towards a stable release and will be implementing some of these protections as a priority.

We currently have warnings on Umbrel saying we're in beta and not to deposit more Bitcoin than you can afford to lose. Our users understand the risk and due to that, the small number of users that were affected by the hacks were very understanding. If we ship AutoSats, Umbrel users may not realise that if their Umbrel gets compromised, they could potentially lose the funds in their exchange account that's connected via AutoSats.

Once we have these protections in place and do our stable release, I think AutoSats would be a really cool app to have on Umbrel. But until then, while Umbrel is still in beta, I think it might be a little too high risk.

Hope that makes sense!

**Comment by bezysoftware** [comment]
@lukechilds thanks for your detailed explanation, I agree it makes sense to wait until the security concerns are resolved, I hope the stable release will be here soon 🙂

**Comment by bezysoftware** [comment]
For anyone interested, I added a bunch of new features in latest versions, including charts and csv export of your data. I've been running the app for over 3 months now on my personal Umbrel instance without any issues

**Comment by nmfretz** [comment]
Hey @bezysoftware, a few things have changed since you submitted AutoSats and apps have now been extracted from this repo. All apps are now found here: https://github.com/getumbrel/umbrel-apps.

Looking through this thread I see that we are waiting for a stable Umbrel release before bringing AutoSats to Umbrel. I am closing this PR because we can no longer merge apps into this repo. We'd love to see you open a PR to our app store repo when we have a stable release! https://github.com/getumbrel/umbrel-apps.

**Pull request closed without merging**
