### PR TITLE
Reformat external storage if it isn't EXT4

### LINKED ISSUE #103: External storage mounter fails to mount exFAT device
When checking for `$UMBREL_EXTERNAL_ROOT/.umbrel`, we should first check if the partition is `ext4`, and if not, nuke it.

### PR DESCRIPTION
**Pull request by lukechilds**
Resolves #103

### CODE REVIEW

**Comment by mayankchhabra** [comment]
Awesome, let's merge this directly since you would've tested it already.

**Comment by lukechilds** [comment]
Haven't tested it quite yet, gimme 5 mins.

**Comment by lukechilds** [comment]
Also testing stuff like this is so quick now with:

```
sudo mkdir /lukechilds-umbrel
cd /lukechilds-umbrel/
sudo chown umbrel:umbrel $PWD
git clone https://github.com/lukechilds/umbrel.git .
git checkout check-external-filesystem
sudo ~/umbrel/scripts/update/update --path /lukechilds-umbrel/
reboot
```

**Comment by lukechilds** [comment]
Tested and working.

**Pull request merged**
