### PR TITLE
Apps/xfce desktop

### PR DESCRIPTION
**Pull request by silverfisk**
# App Submission

### App name
xfce-desktop

### Version
v0.0.1

### One line description of the app
A full Ubuntu desktop environment accessible via any modern web browser.

### Summary of the app
Access your home LAN from anywhere tough Guacamole with a desktop operating system hosted on your Umbrel device.

Guacamole provides access to much of the functionality of a desktop from within your web browser. Although most people use remote desktop tools only when absolutely necessary, we believe that Guacamole must be aimed at becoming a primary means of accessing desktops, and the interface is thus intended to be as seamless and unobtrusive as possible.

This is a packaged setup of containers built and maintained by The LinuxServer.io and nginx teams.
Unlike other containers these Desktops are not designed to be upgraded by Docker. You will keep your home directoy but anything you installed system level will be lost if you upgrade an existing container.

Additional packages and such that you need to persist over upgrades can be configured to install at login time in $HOME/startwm.sh.

It can be access directly on the [LAN](https://umbrel.local:4000/) with a self signed certificate for better performance, but access over TOR is more secure.

### Developer name
@silverfisk

### Developer website
https://github.com/silverfisk/

### Source code link
https://github.com/silverfisk/umbrel

### Support link
https://github.com/silverfisk/

### 256x256 SVG icon
https://svgshare.com/i/_qN.svg

### Gallery images
_(Upload 3 to 5 high-quality gallery images (1440x900px) of your app in PNG format, or just upload 3 to 5 screenshots of your app and we'll help you design the gallery images.)_
Screenshot from 2021-09-05 17-25-33
Screenshot from 2021-09-05 17-27-09
Screenshot from 2021-09-05 17-34-13
Screenshot from 2021-09-05 17-39-37

...

### I have tested my app on:
- [ ] [Umbrel dev environment](https://github.com/getumbrel/umbrel-dev)
- [X] [Umbrel OS on a Raspberry Pi 4](https://github.com/getumbrel/umbrel-os)
- [ ] [Custom Umbrel install on Linux](https://github.com/getumbrel/umbrel#-installation)

### CODE REVIEW

**Comment by lukechilds** [comment]
Woah this is really cool, awesome stuff @silverfisk!

Does webtop require SSL to work or is it possible to use it over plain HTTP on the local network and Tor remotely?

**Comment by silverfisk** [comment]
Thanks @lukechilds ! Yes port 3000 is without SSL, so point TOR there and let the network handle encryption. 4000 with self signed SSL is better than unencrypted for the local access

**Comment by silverfisk** [comment]
I forgot to mention the login credentials:

user: umbrel
password: moneyprintergobrrr

**Comment by mayankchhabra** [comment]
Hey Tom! With Umbrel 0.5, we moved the all the Umbrel apps to their own dedicated repository — [getumbrel/umbrel-apps](https://github.com/getumbrel/umbrel-apps). With this change, new apps (and app updates) go live in the Umbrel App Store in realtime as soon as PRs are merged.

So feel free to open a new PR on that repo if you're interested in shipping xfce. Closing this PR for now. Cheers! :)

**Pull request closed without merging**
