### PR TITLE
Update to lncm/bitcoind:v22.0

### PR DESCRIPTION
**Pull request by lukechilds**
Tested and working but currently missing sources at https://github.com/lncm/docker-bitcoind.

// cc @nolim1t

### CODE REVIEW

**Comment by lukechilds** [comment]
Ah it's in a PR branch but not yet merged: https://github.com/lncm/docker-bitcoind/pull/59#issuecomment-918908987

@nolim1t is the [v22.0 image tagged on Docker Hub](https://hub.docker.com/layers/lncm/bitcoind/v22.0/images/sha256-0e00667f8f084536f45ba680844b6f23a51d3101fb08d8e0ca371ee3f89bc72d?context=explore) safe to use?

**Comment by nolim1t** [comment]
> Ah it's in a PR branch but not yet merged: [lncm/docker-bitcoind#59 (comment)](https://github.com/lncm/docker-bitcoind/pull/59#issuecomment-918908987)
> 
> @nolim1t is the [v22.0 image tagged on Docker Hub](https://hub.docker.com/layers/lncm/bitcoind/v22.0/images/sha256-0e00667f8f084536f45ba680844b6f23a51d3101fb08d8e0ca371ee3f89bc72d?context=explore) safe to use?

Its safe to use.. I've been running it since I've built it. Works with lnd / specter-desktop.

As long as nothing is deprecated on your end too.

**Comment by nolim1t** [comment]
you could use https://github.com/getumbrel/umbrel/pull/983 too

**Comment by lukechilds** [comment]
Ooops sorry missed your other PR.

Thanks for merging!

FYI if you're running this you may also want `deprecatedrpc=addresses` (https://github.com/getumbrel/umbrel/pull/1007/commits/6c964bd5db4f81db322a78c9ef80cd37b1a7045f), Mempool fails without it and any other service that depends on the `addresses` property in RPC responses will too.

**Pull request merged**
