### PR TITLE
Uptime kuma

### PR DESCRIPTION
**Pull request by phaus**
# App Submission

### App name

Uptime Kuma

### Version

1.10.2

### One line description of the app

Uptime Kuma is a self-hosted monitoring tool like 'Uptime Robot'.

### Summary of the app

Uptime Kuma is a self-hosted monitoring tool like 'Uptime Robot'.

Features:

* Monitoring uptime for HTTP(s) / TCP / HTTP(s) Keyword / Ping / DNS Record / Push / Steam Game Server.
* Fancy, Reactive, Fast UI/UX.
 * Notifications via Telegram, Discord, Gotify, Slack, Pushover, Email (SMTP), and 70+ notification services, click here for the full list.
 * 20 second intervals.
 * Multi Languages
  * Simple Status Page
  * Ping Chart
  * Certificate Info
 
### Developer name

Louis Lam

### Developer website

https://uptime.kuma.pet/

### Source code link

https://github.com/louislam/uptime-kuma

### Support link

https://github.com/louislam/uptime-kuma/issues

### Requires

N/A

### 256x256 SVG icon

[icon.svg.zip](https://github.com/getumbrel/umbrel/files/7664188/icon.svg.zip)

### I have tested my app on:
- [x] [Umbrel dev environment](https://github.com/getumbrel/umbrel-dev)
- [x] [Umbrel OS on a Raspberry Pi 4](https://github.com/getumbrel/umbrel-os)
- [x] [Custom Umbrel install on Linux](https://github.com/getumbrel/umbrel#-installation)

### CODE REVIEW

**Comment by lukechilds** [comment]
Thanks for this @phaus, was not familiar with the project but it looks really cool!

Testing now. Would be sweet if we can configure `HTTP_PROXY` or something so we can monitor Tor hidden services too.  😍

**Comment by phaus** [comment]
@lukechilds I contacted the maintainer of uptime-kuma (not me) and it lookes like the support for `HTTP_PROXY` seems to be a little bit more work at the moment: https://github.com/louislam/uptime-kuma/issues/991#issuecomment-988904631 - I might have some time beginning of next year to look into it and might submit a MR for that, but for now, its not supported :-/.

**Comment by lukechilds** [comment]
@phaus thanks for the update!

No worries, we can ship without HTTP_PROXY support. The app is still really useful without it. Would just even better with it.

**Comment by lukechilds** [comment]
Thanks so much for this @phaus (and of course @louislam)!

**Comment by jgmontoya** [comment]
Sorry to comment on an old PR but [I think HTTP_PROXY now works](https://github.com/louislam/uptime-kuma/issues/1624#issuecomment-1120470407) it'd be cool to know how to configure it to monitor onion services

**Pull request merged**
