### PR TITLE
Upgrade bitcoind to 0.21.0

### PR DESCRIPTION
**Pull request by nolim1t**
Some stuff in this release:

```
 - Descriptor wallets
 - Compact block filters over P2P network 
 - Fewer rebroadcast attempts
 - Tor V3 support
 - Schnorr/Taproot code
 ```

[Release notes (Courtesy of bitcoinmagazine)](https://bitcoinmagazine.com/articles/bitcoin-core-0-21-0-released-whats-new)

Now every bitcoin node can serve stuff over neutrino

### CODE REVIEW

**Review by AaronDewes — DISMISSED** [review]

**Comment by nolim1t** [comment]
Im setting this back to draft for a minute. I need to rebuild the release again which will most likely destroy the sha256 hash so that will need to be updated.

**Comment by nolim1t** [comment]
Full [release assets](https://github.com/lncm/docker-bitcoind/releases/tag/v0.21.0%2Bbuild18)

**Review by louneskmt — DISMISSED** [review]

**Comment by lukechilds** [comment]
Yep, seen this.

I think it's best to wait a few weeks minimum after a new Bitcoin Core release so it gets some testing in the wild before including it in Umbrel.

**Review by lukechilds — CHANGES_REQUESTED** [review]
@nolim1t can you remove the checksum pin?

Then this is good to be merged 🎉

**Comment by nolim1t** [comment]
Done

**Review by lukechilds — APPROVED** [review]
Legend!

**Pull request merged**
