### PR TITLE
update sphinx-relay to 2.2.8

### PR DESCRIPTION
**Pull request by Evanfeenstra**
- security updates
- transport token encryption
- HMAC validation
- GitBot integration
- direct payments in tribes
- message "channels" in tribes
- pinned msgs
- greenlight fixes
- better history restore

### CODE REVIEW

**Comment by Evanfeenstra** [comment]
i did `docker pull sphinxlightning/sphinx-relay:v2.2.8` to get the image hash, does that look right? thanks

**Comment by louneskmt** [comment]
When you pull the image, it only gives you the digest for your architecture. You need to pull it, then execute `docker inspect $image` and look for `RepoDigest`.

**Comment by Evanfeenstra** [comment]
Oh cool, thanks for the tip @louneskmt. The hash in the `RepoDigests` matches the one that was printed when i did `docker pull` anyway. So it looks all good

**Comment by lukechilds** [comment]
`docker pull` will dump the multiarch manifest checksum, not the image for the specific arch.

**Comment by louneskmt** [comment]
Sorry my mistake @lukechilds @Evanfeenstra

**Comment by mayankchhabra** [comment]
Hey @Evanfeenstra! Apologies for the delay on this.

With Umbrel 0.5, we moved the all the Umbrel apps to their own dedicated repository — [getumbrel/umbrel-apps](https://github.com/getumbrel/umbrel-apps). With this change, new apps (and app updates) go live in the Umbrel App Store in realtime as soon as PRs are merged.

So feel free to open a new PR on that repo if you'd like to ship this update. Closing this PR for now. Cheers! :)

**Pull request closed without merging**
