### PR TITLE
Update btcpay-server app to v1.3.4

### LINKED ISSUE #1081: Update to the new version of BTCPay Server

### PR DESCRIPTION
**Pull request by louneskmt**
Resolves #1081

Changelogs / releases:
 - https://github.com/btcpayserver/btcpayserver/releases/tag/v1.3.0
 - https://github.com/btcpayserver/btcpayserver/releases/tag/v1.3.1
 - https://github.com/dgarage/NBXplorer/releases/tag/v2.2.16

### CODE REVIEW

**Comment by mccolister1017** [comment]
1.3.2 is out  Tons of bug fixes, and a few improvements!

This also fix a critical vulnerability impacting shared instances.

**Comment by louneskmt** [comment]
Thanks for the heads up @mccolister1017, will push the new update.

**Comment by louneskmt** [comment]
Updated to v1.3.3 (critical security patch).

Changelogs / releases:
 - https://github.com/btcpayserver/btcpayserver/releases/tag/v1.3.2
 - https://github.com/btcpayserver/btcpayserver/releases/tag/v1.3.3

**Review by lukechilds — APPROVED** [review]
Thank you @louneskmt !

**Pull request merged**
