### PR TITLE
App Submission: LNSwap

### PR DESCRIPTION
**Pull request by pseudozach**
# App Submission

### App name
LNSwap

### Version
1.0.0

### One line description of the app
_(max 50 characters)_

Swap Provider client for LNSwap.org

### Summary of the app
_(50 to 200 words)_

LNSwap is an atomic/submarine swap exchange that enables liquidity providers to earn fees by facilitating trustless swaps for users between Lightning/onchain BTC and STX (and optionally other assets) on the Stacks blockchain. 

By installing this app, giving it access to your bitcoin and funding it with STX, you can earn % of fees on each swap completed via your Lightning node or stacks signer account. 
- LNSwap client will register to the aggregator on api.lnswap.org.
- Aggregator will route swap requests from users visiting lnswap.org randomly to clients.
- Client will fulfill swaps by using LND Lightning and onchain funds and auto-generated stacks account (address can be found on the dashboard)
- All swaps are trustless, refunds are processed automatically and funds never leave your device.

### Developer name
pseudozach

### Developer website
https://lnswap.org

### Source code link
_(Link to your app's source code repository.)_

[lnstxbridge-client](https://github.com/pseudozach/lnstxbridge-client)

### Support link
_(Link to your Telegram support channel, GitHub issues/discussions, support portal, or any other place where users could contact you for support.)_

[Discord](https://discord.gg/r5YXZnARGc)

### Requires
- [X] Bitcoin Core
- [ ] Electrum server
- [X] LND

### 256x256 SVG icon
_(Submit an icon with no rounded corners as it will be dynamically rounded with CSS. GitHub doesn't allow uploading SVGs directly, so please upload your icon to an alternate service, like https://svgur.com, and paste the link below.)_

[svg icon](https://svgur.com/s/fDj)

### Gallery images
_(Upload 3 to 5 high-quality gallery images (1440x900px) of your app in PNG format, or just upload 3 to 5 screenshots of your app and we'll help you design the gallery images.)_

image
image
image

### I have tested my app on:
- [X] [Umbrel dev environment](https://github.com/getumbrel/umbrel-dev)
- [X] [Umbrel OS on a Raspberry Pi 4](https://github.com/getumbrel/umbrel-os)
- [ ] [Custom Umbrel install on Linux](https://github.com/getumbrel/umbrel#-installation)

### CODE REVIEW

**Comment by Bowtiedcheetah** [comment]
+1

**Comment by obycode** [comment]
+1 this would be great!

**Comment by txpost** [comment]
+1 much needed

**Comment by 314159265359879** [comment]
+1 I'd love to see this live

**Comment by jiga** [comment]
+1 👍

**Comment by 0xAsteria** [comment]
+1000

**Comment by Dulb26** [comment]
+1

**Comment by morser2017** [comment]
+1

**Comment by ryanwaits** [comment]
+1 LFG

**Comment by santiagosan93** [comment]
+ 1 pls!

**Comment by vict202** [comment]
+1 🚀LFG

**Comment by gigawatson** [comment]
+1 🚀

**Comment by Mistermaddogdugong** [comment]
+1 
Watching this develop as a non-dev has been incredible, a privilege, and feels like history being made.   Well and truly a timely addition.

**Comment by benoror** [comment]
+1 would be awesome!

**Comment by MatthewTang** [comment]
+1 pls

**Comment by spmatt** [comment]
+1

**Comment by dartman10** [comment]
+1

**Comment by koohinp** [comment]
+1

**Comment by mattbombard** [comment]
I love lnswap!! Get it on umbrel ASAP!!

**Comment by Hero-Gamer** [comment]
+ 1

**Comment by awholegnuworld** [comment]
@pseudozach I'm new to Bitcoin and Lightning, and I love your work. +1 to this app submission.

**Comment by nevets963** [comment]
@pseudozach Would you be able package LNSwap and submit this into the official Umbrel App Store located here: https://github.com/getumbrel/umbrel-apps ?

**Comment by nmfretz** [comment]
@pseudozach based on this PR it looks like there is a large amount of interest in getting LNSwap on Umbrel! Have you given any thoughts to submitting this to our App Store here https://github.com/getumbrel/umbrel-apps? or did you end up going the Community App Store route?

I am closing this PR since it can no longer be merged into getumbrel/umbrel with the app store now being a separate repo. Hope to see an app store PR soon!

**Pull request closed without merging**
