### PR TITLE
Update debug

### PR DESCRIPTION
**Pull request by ronnicek**
Adding -T to dmesg to get nicer timestamps, so during debugging it's easier to correlate logs.

### CODE REVIEW

**Review by AaronDewes — APPROVED** [review]

**Review by louneskmt — DISMISSED** [review]

**Review by bguillaumat — DISMISSED** [review]

**Comment by AaronDewes** [comment]
@ronnicek Can you rebase this PR/resolve the conflicts?

**Comment by ronnicek** [comment]
@AaronDewes tried.. but dont know if I didnt mess it up actually, because its strange that there are 35 files changed insted of one :-/ So I assume I will create new PR...

**Comment by ronnicek** [comment]
Hurray.. fixed :)

**Review by AaronDewes — APPROVED** [review]

**Comment by AaronDewes** [comment]
Sorry, this requires a rebase again. @lukechilds Can you please merge this PR once its finished? It's a small PR, and shouldn't take long to review, but if not merged, will have to be rebased many times.

**Comment by ronnicek** [comment]
Damn.. I am totally lame with rebasing. I will open new PR and hope to get merged.

**Pull request closed without merging**
