### PR TITLE
Use github action built (and GPG verified) tor service

### PR DESCRIPTION
**Pull request by nolim1t**
Have a tor container based on debian-slim which is GPG verified and built for cross platform (from the official sources)

### CODE REVIEW

**Comment by nolim1t** [comment]
This looks good

**Comment by mayankchhabra** [comment]
It'd be really great if we could upgrade and use https://github.com/getumbrel/docker-tor

**Comment by nolim1t** [comment]
I'm not the maintainer of that project

**Comment by mayankchhabra** [comment]
But you can make a PR?

**Comment by mayankchhabra** [comment]
Hey, @nolim1t closing this due to inactivity. Feel free to make a PR on https://github.com/getumbrel/docker-tor with your upgrades if you'd like to.

**Pull request closed without merging**
