### PR TITLE
Update to LND v0.13.1

### PR DESCRIPTION
**Pull request by nolim1t**
Release notes [here](https://github.com/lightningnetwork/lnd/releases/tag/v0.13.0-beta)

### CODE REVIEW

**Comment by jgmontoya** [comment]
New update: [v0.13.1](https://github.com/lightningnetwork/lnd/releases/tag/v0.13.1-beta.rc1)

**Comment by nolim1t** [comment]
Thanks , its still a release candidate but will be tracking this

**Comment by AaronDewes** [comment]
This PR also requires changes to umbrel-middleware, just FYI

**Comment by nolim1t** [comment]
> This PR also requires changes to umbrel-middleware, just FYI

hmm they are using deprecated functionality?

**Comment by AaronDewes** [comment]
Removed functionality. The wallet unlocking logic channged in 0.13

**Comment by jgmontoya** [comment]
[v0.13.1-beta released](https://github.com/lightningnetwork/lnd/releases/tag/v0.13.1-beta) :smile:

**Comment by AaronDewes** [comment]
> [v0.13.1-beta released](https://github.com/lightningnetwork/lnd/releases/tag/v0.13.1-beta) smile

Already supported by my Citadel node, hopefully Umbrel will get it soon.

**Comment by AaronDewes** [comment]
Sorry, the actual change is that the way a locked wallet can be detected changed.

**Comment by nolim1t** [comment]
I also propose we use the experimental tag which gives us access to the following config which will help with routing issues on neutrino nodes.

```
[Routing]
routing.assumechanvalid=1
```

And switch back to the mainline neutrino switcher  and suggest changes in that. No reason to keep forks of packages.

**Pull request closed without merging**
