### PR TITLE
Replace git logic with a single git command

### PR DESCRIPTION
**Pull request by lukechilds**
This is functionally equivalent.

### CODE REVIEW

**Comment by lukechilds** [comment]
Actually it's not the same, a fresh clone will fail if the directory contains files.

Is think `git reset --hard tags/v0.1.3-beta` is still redundant though.

**Comment by mayankchhabra** [comment]
Lol literally had to make an emergency release yesterday because I did the same mistake: https://github.com/getumbrel/umbrel/pull/21/files

**Comment by lukechilds** [comment]
Do you know the reasoning behind `git reset --hard`?

**Comment by mayankchhabra** [comment]
Not really, AFAIU you're right — it seems redundant since no local changes are made between `git checkout` and `git reset`. I just reverted it back to what it was. 

cc @nolim1t

**Comment by nolim1t** [comment]
I'm not just "flattening the curve" .. I'm destroying it completely

no-flattnening

**Pull request closed without merging**
