### PR TITLE
Update lncm/lnd to 0.12.0

### PR DESCRIPTION
**Pull request by nolim1t**
Update LND to 0.12.0 

Thanks @AaronDewes for reminding about it

### CODE REVIEW

**Comment by lukechilds** [comment]
Thanks @nolim1t!

Are you able to remove the checksum to keep inline with the atomic commit philosophy?

A follow up PR to pin all Docker images would be very welcome!

**Review by lukechilds — CHANGES_REQUESTED** [review]
Thanks @nolim1t!

Are you able to remove the checksum to keep inline with the atomic commit philosophy?

A follow up PR to pin all Docker images would be very welcome!

**Comment by nolim1t** [comment]
Ok done

**Review by lukechilds — APPROVED** [review]
Legend!

**Pull request merged**
