### PR TITLE
Update Jam to `v0.0.5`

### PR DESCRIPTION
**Pull request by theborakompanioni**
This version includes:
- joinmarket-webui: [v0.0.5](https://github.com/joinmarket-webui/joinmarket-webui/releases/tag/v0.0.5)
- joinmarket-clientserver: [v0.9.5](https://github.com/JoinMarket-Org/joinmarket-clientserver/releases/tag/v0.9.5)

All notable changes of the UI can be seen in the [Jam `v0.0.5` changelog](https://github.com/joinmarket-webui/joinmarket-webui/blob/v0.0.5/CHANGELOG.md)

Updates to the image:
- Colorize bash output [#28](https://github.com/joinmarket-webui/joinmarket-webui-docker/pull/28)

### CODE REVIEW

**Comment by louneskmt** [comment]
Hey, thanks for this PR!

Ongoing testing:
- [x] Checksums are correct and are for a multiarch manifest
- [x] Registry has been updated
- [ ] Update working on arm64
- [ ] Update working on amd64

**Comment by louneskmt** [comment]
My bad, working well on testnet. Thanks!

**Comment by theborakompanioni** [comment]
> @theborakompanioni I'm trying to test it, but I get a "No Connection to backend: the server reported a problem" at every step (first when I created the wallet, then trying to unlock it). Looks like `jamwalletd` is crashing each time. Maybe JAM doesn't support regtest? If so, I can consider it as “working on amd64".

Hmm.. it should work on `regtest` also, as we are testing all of the features locally. The only difference I can think of is that Jam's dev env starts with `100` blocks initially.. I will check if `jmwalletd` maybe does not like having too little blocks. I cannot think of anything other than that right now.. Would you share your config params?

> My bad, working well on testnet. Thanks!
:muscle:

**Comment by louneskmt** [comment]
It was a brand new regtest instance, so no blocks, etc. It might haven't liked that.

**Comment by theborakompanioni** [comment]
> It was a brand new regtest instance, so no blocks, etc. It might haven't liked that.

I will verify that as soon as possible. Thanks for the heads-up! On a side note.. is there a way for Umbrel Apps to wait for IBD to be completed?

**Comment by louneskmt** [comment]
Not out of the box. But I guess if you're connected to Bitcoin RPC, you can fetch that info.

**Review by louneskmt — APPROVED** [review]

**Comment by lukechilds** [comment]
Thanks @louneskmt and @theborakompanioni! ❤️

**Pull request merged**
