### PR TITLE
App Submission: Urbit on Umbrel

### PR DESCRIPTION
**Pull request by mopfel-winrux**
# App Submission

### App name

Urbit on Umbrel

...

### Version

0.1.0

...

### One line description of the app

Run your Urbit on your Umbrel, use your Umbrel as %btc-provider backend

...

### Summary of the app

Urbit is a personal server for self-sovereign personal & networked computing. Nock, a functional combinator, is built into Hoon, a system programming language, used to implement Arvo, a deterministic operating system, that communicates over Ames, a decentralized, encrypted P2P network.

This app helps you boot and manage Urbit instances on your Umbrel. It provides a simple management GUI, start and stop operations, and passes your `+code` through the interface.

...

### Developer name

`~mopfel-winrux`, `~sitful-hatred`

Credit to `~timluc-miptev`, `~master-forwex`, `~sipsen-pilser` & `~rivpyl-sidfyl`

...

### Developer website

[Github](https://github.com/mopfel-winrux/urbit-umbrel)

...

### Source code link

[Github Repo](https://github.com/mopfel-winrux/urbit-umbrel)

...

### Support link

[Github Issues](https://github.com/mopfel-winrux/urbit-umbrel)

...

### Requires

- [] Bitcoin Core
- [] Electrum server
- [ ] LND

### 256x256 SVG icon

Urbit on Umbrel Logo

...

### Gallery images

Urbit on Umbrel Start Page
Urbit on Umbrel Code Page
Urbit %garden Basic
Urbit %garden Populated

...

### I have tested my app on:

- [X] [Umbrel dev environment](https://github.com/getumbrel/umbrel-dev)
- [X] [Umbrel OS on a Raspberry Pi 4](https://github.com/getumbrel/umbrel-os)
- [ ] [Custom Umbrel install on Linux](https://github.com/getumbrel/umbrel#-installation)

### CODE REVIEW

**Comment by mopfel-winrux** [comment]
Looks like github caches the SVG so I can't update it. the PR links to one of a correct size

**Comment by yapishu** [comment]
A few additional notes to throw in -- there are 3 exposed ports, which by default are:
- TCP/8090 -- webUI for both management interface and Urbit OS (management UI located at `/launch`)
- TCP/50002 -- RPC port that allows urbits to use the Umbrel as a backend for the native Bitcoin wallet's provider server 
- UDP/34343 -- Ames port, Urbit's native networking protocol; this doesn't have to be exposed but doing so improves latency

The web UI can be exposed over a hidden service, but Urbit's native networking is UDP and thus cannot be tunneled through Tor. Right now there is no user authentication, so publicly exposing the interface (via Tor or otherwise) is not recommended. 

Urbit's Bitcoin software consists of `%btc-provider`, a server/relay that connects to a full node, and `%btc-wallet`, the user-facing GUI wallet app. The wallet must be connected to a provider in order to function, but any Umbrel with this app installed can function as a provider automatically. To connect the provider to your Umbrel: 

```
dojo> |rein %bitcoin [& %btc-provider]
dojo> =network %main
dojo> :btc-provider +bitcoin!btc-provider/command [%set-credentials api-url='https://addresshere' network]
```

To whitelist clients: 

```
:: Individual ships ::
dojo> :btc-provider +bitcoin!btc-provider/command [%add-whitelist [%users users=(sy ~[~wallet-hodler])]]
:: Group members (provider ship must be a member) ::
dojo> :btc-provider +bitcoin!btc-provider/command [%add-whitelist [%groups groups=(sy ~[[~sampel %group-name]])]]
:: %kids ::
dojo> :btc-provider +bitcoin!btc-provider/command [%add-whitelist %kids ~]
:: Public whitelisting ::
dojo> :btc-provider +bitcoin!btc-provider/command [%add-whitelist %public ~]
```

**Comment by lukechilds** [comment]
This is so cool, excellent work guys! And thanks for the detailed explanation!

Just to clarify I understand this correctly. This app does two totally different things:

1) It allows you to run a fully functional Urbit instance
2) It runs a service that allows an Urbit instance (external or the one included in this app) to use this Umbrel as a source for Bitcoin data.

Is that correct?

I've just tested it out, Urbit worked great but I didn't seem to be able to get the Bitcoin app working.

I ran the commands provided from the web terminal:

Screenshot 2022-02-08 at 19 20 37

But got shown this when opening the Bitcoin app:

Screenshot 2022-02-08 at 19 20 42

Is that expected or is there something else I need to do?

>TCP/50002 -- RPC port that allows urbits to use the Umbrel as a backend for the native Bitcoin wallet's provider server

Are you aware that's the same port that Electrum uses for SSL by default? It might be worth using a different port for the Urbit proxy just to avoid confusion.

>The web UI can be exposed over a hidden service, but Urbit's native networking is UDP and thus cannot be tunneled through Tor. Right now there is no user authentication for the management UI, so publicly exposing the interface (via Tor or otherwise) is not recommended.

Would be really nice if we could ship with UI access over Tor. Lots of Umbrel users access remotely over Tor. We also provide an environment variable `$APP_PASSWORD` to make this super simple to support. It's a cryptographically secure hex string unique to your app that will be shown to the user in the Umbrel UI. You can then check for it in the management UI.

If you wanted to support this quickly you can just add HTTP basic auth that checks for `umbrel:$APP_PASSWORD`.

**Comment by lukechilds** [comment]
>you just need to enter your ship's @p (name) in the field you screenshot

Ahhhh, missed that, thanks!

>It started out as two apps that we merged together

Got it. I actually think this makes a lot of sense to ship as two seperate apps. The use case and kind of people who want to do these two things are very different.

Existing Urbit users who already run Urbit and want to use their Umbrel as a Bitcoin source will want the proxy use case.

Umbrel users who may not be too familair with Urbit and are interested in checking out what Urbit is would be interested in running Urbit directly on their Umbrel. They also may not necessarily want to pair it with their Bitcoin node. We're in the process of migrating Bitcoin to the app store, so some users in the future might not even have the Bitcoin app installed. Bitcoin Core would be a pretty heavy dependency of Urbit if it's not otherwise needed.

The way ideally this would work in my head is two apps:

An "Urbit" app that just runs Urbit and displays the Urbit UI to the user. Ideally there wouldn't be an additional UI layer on top for starting/stoping Urbit. That would by controlled at the Umbrel level by starting/stopping the Urbit app.

An "Urbit Bitcoin Server" (or something along those lines) app that runs the proxy. The web UI could just be a static HTML page that says something like "Add http://umbrel.local:1234 as a provider on your Urbit" along with some more detailed instructions.

That's what makes the most sense to me, let me know what your thoughts are.

**Comment by mopfel-winrux** [comment]
> An "Urbit" app that just runs Urbit and displays the Urbit UI to the user. Ideally there wouldn't be an additional UI layer on top for starting/stoping Urbit. That would by controlled at the Umbrel level by starting/stopping the Urbit app.

I think you need the UI for users to upload a pier or key when you initially boot up your Urbit. Additionally, some users juggle multiple piers at a time. 

I think we can split them up again if you'd like that. The app as it is now doesn't use up much resources when Urbit isn't running, but if Bitcoin is going to the Umbrel app store it may make sense to split them.

**Comment by lukechilds** [comment]
>I think you need the UI for users to upload a pier or key when you initially boot up your Urbit. Additionally, some users juggle multiple piers at a time.

Ahhh ok, yeah that makes sense.

>I think we can split them up again if you'd like that. The app as it is now doesn't use up much resources when Urbit isn't running, but if Bitcoin is going to the Umbrel app store it may make sense to split them.

Yeah that sounds great to me, moving Bitcoin to the app store is going to be shipped soon, we're actively working on it right now.

Also:

Screenshot 2022-02-08 at 20 23 07

It works 🚀

**Comment by yapishu** [comment]
Okay, that makes sense. We'll put together a UI for the Bitcoin connector and add basicauth to the ship manager. Should we resubmit both, or just the connector?

**Comment by lukechilds** [comment]
Oh also just to let you know, we're aiming for an Umbrel release tomorrow. It would be awesome if this can make it into that release. Of course no pressure if you need more time, we can include you in the next release (probably ~2 weeks from now) if you can't make it.

**Comment by mopfel-winrux** [comment]
We'll try and get it done today so we can be in the release tomorrow!

**Comment by lukechilds** [comment]
Awesome, looking forward to seeing it!

**Comment by mopfel-winrux** [comment]
The urbit-umbrel image is updated to not include the Bitcoin connector. Also we added a basic auth to the main page.

We had some trouble with `$APP_PASSWORD` not being passed to the container so there's an if-else statement in the start.sh script where it sets the login to `umbrel/default` if `$APP_PASSWORD` isn't populated. If it is the login is `umbrel/$APP_PASSWORD`

**Comment by mopfel-winrux** [comment]
Ignore the defualt stuff. We setup the APP_PASSWORD wrong in the docker-compose. it should work now. I do have to get the $APP_PASSWORD from the docker image though.

**Comment by yapishu** [comment]
The Bitcoin connector app has been submitted separately [here](https://github.com/getumbrel/umbrel/pull/1243)

**Comment by lukechilds** [comment]
Wow, incredible work guys, super fast! Testing now!

**Comment by lukechilds** [comment]
>I do have to get the $APP_PASSWORD from the docker image though.

@mopfel-winrux you can run this to dump container env vars:

```
./scripts/app compose urbit-umbrel exec urbit-umbrel env
```

**Comment by lukechilds** [comment]
Tested and working flawlessly, this is really impressssive stuff guys, I'm in awe!

Also how about changing the name from "Urbit on Umbrel" to just "Urbit"? I think it looks cleaner and the "on Umbrel" part is implied since users know they're installing from the Umbrel app store. Thoughts?

**Comment by lukechilds** [comment]
Guys are you able to "Allow edits from maintainers" on this PR branch so I can push some changes?

**Comment by lukechilds** [comment]
Ok made the latest changes in https://github.com/getumbrel/umbrel/pull/1246 and merged that in the interest of saving time to make this release. It's tested and working great over Tor too, please let me know if you have an issue with any of the changes I made and I can revert them!

**Comment by mayankchhabra** [comment]
Really amazing work on both Urbit and the Bitcoin connector app, @mopfel-winrux and @yapishu! 👏 

Congrats on the [launch](https://twitter.com/getumbrel/status/1491438251248611328)! The response has been great :)

[Here](https://github.com/getumbrel/umbrel-apps-gallery/tree/master/urbit) are the gallery images and the app icon for the Urbit app. If you ever want to change/update them, feel free to directly open a PR at [getumbrel/umbrel-apps-gallery](https://github.com/getumbrel/umbrel-apps-gallery). Keep up the good work!

**Pull request closed without merging**
