### PR TITLE
App Submission - "Podcasting 2.0: Boosts"

### PR DESCRIPTION
**Pull request by daveajones**
# App Submission

### App name
Podcasting 2.0: Boosts

### Version
0.1.4

### One line description of the app
Shows boosts and boost-a-grams from Podcasting 2.0 enabled apps.

### Summary of the app
This app shows boosts and boost-a-gram messages coming in to your Lightning node from your listeners who are using Podcasting 2.0 apps.  

### Developer name
Podcastindex.org

### Developer website
https://podcastindex.org

### Source code link
https://github.com/Podcastindex-org/helipad

### Support link
https://podcastindex.social

### Requires
- [ ] Bitcoin Core
- [ ] Electrum server
- [X] LND

### 256x256 SVG icon
https://raw.githubusercontent.com/Podcastindex-org/art-graphics-logos/master/pci_avatar.svg

### Gallery images
http://dave.sobr.org/enc/1638548718.646_boostagramsss1.png
http://dave.sobr.org/enc/1638548718.646_boostagramsss2.png
http://dave.sobr.org/enc/1638548718.646_boostagramsss3.png

### I have tested my app on:
- [X] [Umbrel dev environment](https://github.com/getumbrel/umbrel-dev)
- [X] [Umbrel OS on a Raspberry Pi 4](https://github.com/getumbrel/umbrel-os)
- [X] [Custom Umbrel install on Linux](https://github.com/getumbrel/umbrel#-installation)

### CODE REVIEW

**Comment by jamescridland** [comment]
I'm very much looking forward to this app - it's been the subject of much discussion.

**Comment by brianoflondon** [comment]
I've been testing this app for @daveajones during development on my completely standards Raspberry Pi 4 with 4meg based Umbrel. It works well. Looking forward to seeing it in the App Store.

Value 4 Value within Podcasting is going to be a very important use case for Lightning.

**Comment by Everything-Everywhere** [comment]
I am looking forward to approval. This is a critical app for all podcasters who use Umbrel

**Comment by drebscott** [comment]
looking forward to this app getting approved and rolled into the next update.

**Comment by lukechilds** [comment]
Thanks for this @daveajones reviewing now. Certainly looks like you have lots of excited users already!

If my understanding is correct this is an app aimed at podcast authors to see payments coming from their users, the app is not aimed at podcast consumers, is that right?

Is there a way I can test this app without being a podcaster to see what the functionality looks like?

I've got your branch running locally and I'm just seeing the "No data to show yet. Building the initial database may take some time..." message. How long should I expect to see that before something else shows up? It's been like that for about 30 minutes, am I just stuck on that screen because I don't have any boost-a-gram messages?

Also jsut seeing:

```
web_1  | ** Supplied boostcount from call: [20]
web_1  | ** get_last_boost_index_from_db() -> [29]
web_1  | Current index: 29
```
 repeated in the logs.

**Comment by brianoflondon** [comment]
> Thanks for this @daveajones reviewing now. Certainly looks like you have lots of excited users already!
> 
> If my understanding is correct this is an app aimed at podcast authors to see payments coming from their users, the app is not aimed at podcast consumers, is that right?
> 
> Is there a way I can test this app without being a podcaster to see what the functionality looks like?

I have some test scripts that can send out boostagrams given a public node address. I can send you a few if you want to pass your public address to me. Feel free to reach out to me on Telegram (t.me/brianoflondon) to keep that private if you prefer. 

This functionality is really only for podcast creators who put a Lightning Value block in their Podcast's RSS feed. Users of new Podcasting 2.0 Podcast listening apps can send them sats while they listen and boostagrams which have messages embedded.

I probably can't do much more until Sunday morning however but happy to boost you a few sats then using my scripts. The other questions are better answered by Dave. He also may have a way to send you test boosts given your public node address.

**Comment by brianoflondon** [comment]
I have a MongoDB database with 4000+ invoices with a mixture of Boosts and Streaming payments that serves as a very good test sample though I'm unclear how that could be put back into someone else's node.

**Comment by lukechilds** [comment]
Got it, thanks for the explanation guys!

Just DMd @brianoflondon on Telegram.

**Comment by lukechilds** [comment]
Just checking but currently we have the app name down as "Podcasting 2.0: Boosts" which I think is a little long. I see the code repo is called Helipad.

Maybe it would be better to rename the app to either "Helipad" or "Boosts". The title will be accompanied with the tagline "Shows boosts and boost-a-grams from Podcasting 2.0 enabled apps." so it'll be clear the app is related to Podcasting 2.0.

What do you think @daveajones?

**Comment by lukechilds** [comment]
Also how did you get on with the changes discussed on Telegram @daveajones? Once you've pushed a new image with those I think this is good to merge! 🚀

**Comment by daveajones** [comment]
Yep I’m good with the name change. I’ll do that. 

The image location changes and such are working fine. I’m just finishing up a change to the configuration discovery (env, then config file, then fallback to known locations) for the db path, port, macaroon, etc.

Almost done and I’ll update the PR and ping here when ready.

**Comment by lukechilds** [comment]
Merged as https://github.com/getumbrel/umbrel/pull/1174 🚀

**Pull request closed without merging**
