### PR TITLE
Remove web logs

### PR DESCRIPTION
**Pull request by lukechilds**
Related: https://github.com/getumbrel/umbrel-dashboard/pull/330

This just tails syslog, which doesn't contain much useful information any more since https://github.com/getumbrel/umbrel/pull/709.

Instead, if users want to view the logs, they should view debug information via https://github.com/getumbrel/umbrel/pull/391.

### CODE REVIEW

**Comment by AaronDewes** [comment]
Okay, I'll close my UI improvements PR in umbrel-frontail then.

**Comment by AaronDewes** [comment]
Don't forget to remove this from SECURITY.md too

**Comment by lukechilds** [comment]
>Okay, I'll close my UI improvements PR in umbrel-frontail then.

Ah yes sorry about that. It would be quite a bit of work to continue using frontail after #709. And it doesn't make sense to work on it when #391 more or less achieves the same without the data leak issue.

>Don't forget to remove this from SECURITY.md too

Thanks, completely forget about that!

**Comment by AaronDewes** [comment]
Yes, #391 is great. @mayankchhabra would be great to get a design review / design improvements from you for the dashboard debug UI.

@louneskmt And you can probably remove the debug option from the loading screen, the loading screen was nearly removed.

**Pull request merged**
