### PR TITLE
Upgrade ItchySats app to `0.4.10`

### PR DESCRIPTION
**Pull request by scratchscratchscratchy**
0.4.8 includes:
- Short positions, you can now go long and short
- Various Bugfixes

(0.4.9 was a patch release that is irrelevant for the Umberl container)

0.4.10 includes:
- A banner celebrating Bitcoin 2022 conference in Miami :)

### CODE REVIEW

**Comment by louneskmt** [comment]
Hey, thanks for this PR!

Ongoing testing:
- [x] Checksums are correct and are for a multiarch manifest
- [x] Registry has been updated
- [ ] Update working on arm64
- [ ] Update working on amd64

**Comment by louneskmt** [comment]
I'm able to start the image (see logs below), but I can't access the web UI. I'm running on testnet. Any idea?

image

**Comment by scratchscratchscratchy** [comment]
> I'm able to start the image (see logs below), but I can't access the web UI. I'm running on testnet. Any idea?
> 
> image

@louneskmt in addition to what @luckysori said: The initial run usually takes some time, because the application waits until the `electrs` container is ready (i.e. reachable). For me, after updating to the latest branch it always takes up to a minute for the UI to be available because it gets blocked on `electrs` RPC still warming up.

**Comment by louneskmt** [comment]
Thanks guys, that makes sense. Can you change `mainnet` to `$BITCOIN_NETWORK` in the compose file? That way the network can be set dynamically.

**Comment by klochowicz** [comment]
> Thanks guys, that makes sense. Can you change `mainnet` to `$BITCOIN_NETWORK` in the compose file? That way the network can be set dynamically.

Thanks for the suggestion!  I have updated the docker-compose file. Please bear in mind that we don't have a testnet maker currently online - so the testnet UI will show that the maker is offline.

**Comment by louneskmt** [comment]
Thanks @klochowicz, it's working great! Now it autodetects the current network 👌

**Review by louneskmt — APPROVED** [review]

**Comment by lukechilds** [comment]
Thanks @louneskmt @scratchscratchscratchy @klochowicz. Congrats on shipping shorts!

**Pull request merged**
