### PR TITLE
Add Caravan app

### PR DESCRIPTION
**Pull request by bguillaumat**
# App Submission

### App name
Caravan

### Version
0.3.5

### One line description of the app
_(max 50 characters)_

Bitcoin multisig coordination software

### Summary of the app
_(50 to 200 words)_

Caravan is making bitcoin multisig custody easier and safer through transparency and standards.

Caravan is a coordination software. It connects to a source of consensus and your keys to build and interact with multisig bitcoin addresses.

### Developed by
Unchained Capital

### Developer website
https://unchained-capital.com/

### Source code repository
https://github.com/unchained-capital/caravan

### Support link
_(Link to your Telegram support channel, GitHub issues/discussions, support portal, or any other place where users could contact you for support.)_

https://t.me/unchainedcap

### Uses
- [x] Bitcoin Core (Can be entered by the user in the app)
- [ ] Electrum server
- [ ] LND

### 256x256 SVG icon
_(GitHub doesn't allow uploadig SVGs directly. Upload your file to an alternate service, like https://svgur.com, and paste the link below.)_

ALT

### App screenshots
_(Upload 3 to 5 high-quality screenshots (at least 1280x800px) of your app in PNG format.)_

image
image
image

### I have tested my app on:
- [x] [Umbrel dev environment](https://github.com/getumbrel/umbrel-dev)
- [x] [Umbrel OS on a Raspberry Pi 4](https://github.com/getumbrel/umbrel-os)
- [ ] [Custom Umbrel install on Linux](https://github.com/getumbrel/umbrel#-installation)

### CODE REVIEW

**Comment by louneskmt** [comment]
Thanks for working on this @bguillaumat, the dockerized app works fine.

As the way Caravan is built doesn't allow us to configure the bitcoind connection via through environment variables as we usually do (see https://github.com/unchained-capital/caravan/issues/140), we will certainly need to add post-install instructions in the Dashboard for the user to do it manually. 

We should also display a warning about the use of the Blockstream API on clearnet if the user doesn't configure the connection to their Umbrel's Bitcoin Core.

**Comment by louneskmt** [comment]
Also, the SVG icon is not found @bguillaumat.

**Comment by bguillaumat** [comment]
Hey @louneskmt, yes sadly no env var... We can eventually create a fork of their repo and add the part of connection updated to handle the env.

And I will update this svg don't know wtf happen with the previous one

**Comment by louneskmt** [comment]
> We can eventually create a fork of their repo and add the part of connection updated to handle the env.

I don't really think it's a good idea for the security reasons exposed in the issue I attached above.

**Comment by bguillaumat** [comment]
Yes you're right, then manually it will be done :smile:

(I don't know if it can support the tor connection)

**Comment by lukechilds** [comment]
Should we close this PR?

Since after discussion in Keybase it seems like Caravan is not a suitable app for Umbrel since it requires a client side connection to Bitcoin Core.

**Comment by bguillaumat** [comment]
Totally! Closing it

**Pull request closed without merging**
