### PR TITLE
Update specter-desktop app to 1.2.2

### PR DESCRIPTION
**Pull request by nolim1t**
Update specter desktop app to 1.2.2

### CODE REVIEW

**Review by louneskmt — APPROVED** [review]

**Comment by weisjohn** [comment]
@nolim1t can you immediately bump this to v1.2.2? 
https://github.com/cryptoadvance/specter-desktop/releases/tag/v1.2.2

**Comment by nolim1t** [comment]
Ok now updated

**Comment by weisjohn** [comment]
@louneskmt I tested this on my umbrel by applying the diff, restarting the umbrel service and things work well.  I can still see my Specter Desktop app and it functions well.

**Review by louneskmt — DISMISSED** [review]

**Review by weisjohn — APPROVED** [review]

**Review by weisjohn — CHANGES_REQUESTED** [review]
So, I actually believe this should not be merged at this time. 
With Specter Desktop v1.1.0 I **can** make a wallet,
With Specter Desktop v1.2.1 or v1.2.2 I **can not** make a wallet.

I believe this has to do w/ this modification to how they make wallets now: https://github.com/cryptoadvance/specter-desktop/commit/790bfbbb050bf751509264f2f49a72793ac8041a

**Comment by nolim1t** [comment]
Wouldn't creating a wallet be something thats addressed directly with Specter Desktop? 

This has nothing to do with Umbrel.

**Comment by louneskmt** [comment]
Sure @nolim1t. @weisjohn point is that we shouldn't merge this version in Umbrel if it doesn't work yet. It would break Specter app.

**Comment by nolim1t** [comment]
For 1.2.2 to fully work we would need to do the following:

* Get compiled in sqlite3 support (see https://github.com/lncm/docker-bitcoind/pull/51) .. Am building this as we speak.
* Pull the new bitcoind (this would be a good time to use image pinning for all the containers actually)

**Comment by nolim1t** [comment]
this can happen after #596 is merged

**Comment by k9ert** [comment]
As https://github.com/lncm/docker-bitcoind/issues/50 is closed, there is now nothing anymore blocking this, no?

**Comment by nolim1t** [comment]
Yes we need to wait for #596 to be merged before this can work.

Whenever enough testing is done by the umbrel guys

**Comment by weisjohn** [comment]
#596 is merged, happy to retest here?

**Comment by lukechilds** [comment]
@weisjohn thanks, that would be great!

Also testing it on my end but confirmation from you that the error you saw last time is resolved would be much appreciated!

**Comment by lukechilds** [comment]
Tested and working well, thanks @nolim1t!

**Review by lukechilds — APPROVED** [review]

**Pull request merged**
