### PR TITLE
Add Elements Core

### PR DESCRIPTION
**Pull request by tiero**
# App Submission

### App name

Elements Core

### Version
0.21.0.2

### One line description of the app

Elements core is a full node and wallet software for the Liquid Network

### Summary of the app

Elements is an open source full node implementation to run the Liquid Network, a Bitcoin layer-2 solution enabling the fast, confidential settlement and issuance of digital assets, such as stablecoins, security tokens, and other financial instruments, on top of the Bitcoin timechain.

### Developer name

Elements Core Developers 

### Developer website

https://elementsproject.org

### Source code link

https://github.com/ElementsProject/elements

### Support link

https://t.me/liquid_community

### Requires

- [x] Bitcoin Core

### 256x256 SVG icon

https://liquid.net/static/images/liquid_logo.svg

### Gallery images

https://raw.githubusercontent.com/tiero/elements-web/master/elements-ui-mockup.png

### I have tested my app on:
- [x] [Umbrel dev environment](https://github.com/getumbrel/umbrel-dev)
- [x] [Umbrel OS on a Raspberry Pi 4](https://github.com/getumbrel/umbrel-os)
- [ ] [Custom Umbrel install on Linux](https://github.com/getumbrel/umbrel#-installation)

### CODE REVIEW

**Comment by lukechilds** [comment]
Thanks for working on this @tiero! Are you planning to add a web UI layer to this app? It's a requirement of Umbrel apps that they display some kind of web UI to the user. This doesn't have to be anything crazy like a full blown Liquid web wallet, it can just be a static page saying that the service is running and ideally would provide some connection details.

Also should we enable `validatepegin` and configure it to talk to Bitcoin Core? It's not clear to me what the benefit would be of running a Liquid full node without validating the BTC peg.

**Comment by tiero** [comment]
> some kind of web UI to the user


I can add a container in the compose with server side rendered web page that call `getblokchchaininfo` and displays the response. (to avoid cors errors)


What about connection details? Do you usually expose into the wild the Bitcoin Core RPC? Or do you mean just the p2p port for other nodes to connect?

Is there a way to know (so we can inject in the container of the web app) the current host:port Umbrel is running? ie. the onion endpoint I assume? 

> Also should we enable `validatepegin` and configure it to talk to Bitcoin Core? It's not clear to me what the benefit would be of running a Liquid full node without validating the BTC peg.

Yep def valuable to validate BTC peg, I guess a bit more resource intensive the initial IBD, but since BTC is already there best to add. Will do

**Comment by lukechilds** [comment]
>I can add a container in the compose with server side rendered web page that calls getblokchchaininfo and displays the response. (to avoid cors errors)

Sounds great!

>What about connection details? Do you usually expose into the wild the Bitcoin Core RPC? Or do you mean just the p2p port for other nodes to connect?

Yeah so ideally you would show the RPC/P2P port along with RPC username and password. We would normally encourage putting that behind a password protected web UI using `$APP_PASSWORD` but you don't need to worry about that. We're about to ship a new feature that handles this at the Umbrel level so apps won't need to do this any more.

>Is there a way to know (so we can inject in the container of the web app) the current host:port Umbrel is running? ie. the onion endpoint I assume?

Yeah you can use `$APP_HIDDEN_SERVICE`.

>Yep def valuable to validate BTC peg, I guess a bit more resource intensive the initial IBD, but since BTC is already there best to add. Will do

Awesome!

**Comment by tiero** [comment]
@lukechilds  I added a very basic web page that connects to the Elements node and display connection details. 

Some help needed:

1. Can we make rpcbind, rpcallowip options more stringent?
2. I do not have more than one single page, so can't really upload more than one screenshot
3. I can't really test on RaspberryPi since always traveling last weeks and i have an Apple M1 and I am really struggling to make it work the umbrel dev :/ the images are multiarch, I used them on arm64 individually in the past, so should work imo

**Comment by lukechilds** [comment]
Awesome, excited to test it out! Btw I've been playing around with Marina on Liquid Testnet and I really love what you guys are doing!

>Can we make rpcbind, rpcallowip options more stringent?

You could do, we can pass in the IP of the container so you can do something like:

```yaml
    command:
      ...
      - -rpcbind=${ELEMENTS_CORE_IP}
      - -rpcallowip=${GATEWAY_IP}/16
```

But I actually would reccomend keeping it as is. We plan to implement network level sandboxing in Umbrel so that by default each app runs on it's own isolated network. By one app registering another app as a dependency and the user confirming this is ok at install time they will be allowed network access between eachother.

To me network access control seems like a job better left to Umbrel than to be re-implemented menually by each app. So I would be in favour of apps having slightly more relaxed networking rules and relying on Umbrel's sandboxing to lock stuff down.

Of course this sandboxing isn't implemented today so you could lock it down at the app level if you think it's necessary. I personally think it's fine as is.

>I do not have more than one single page, so can't really upload more than one screenshot

That's no problem, the page looks great from your screenshot! We can probably re-use that page 3 times with some different title text for the app slides, we've done that before for some single page apps.

We can whip something up and get your feedback on that.

>I can't really test on RaspberryPi since always traveling last weeks and i have an Apple M1 and I am really struggling to make it work the umbrel dev :/ the images are multiarch, I used elements image on arm64 individually in the past, so should work , but would love to test it out somehow

Are you on the latest version of umb rel-dev? We recently pushed some fixes for M1 Macs. Unfortunately you need a professional license of Parallels for it work, no OSS Vagrant backends that support M1 Macs currently.

If that's an issue no biggie, I can get it running on a VM locally and give you access to have a poke around.

**Comment by tiero** [comment]
@lukechilds seems it works flawless! 

Thanks to @dabloem for help in testing and finding/fixing errors with my conf

**Comment by lukechilds** [comment]
@tiero awesome!

Just to let you know, this will definitely make it into the next release. We're just in the process of making some changes which will conflict with this PR which is why we haven't merged it yet. Don't worry though, the changes will be minimal and we'll resolve the conflicts.

**Comment by mayankchhabra** [comment]
Really nice work packaging Elements, @tiero! 👏 Congrats on the [launch](https://twitter.com/umbrel/status/1525115637810745345)! 🎉

[Here](https://github.com/getumbrel/umbrel-apps-gallery/tree/master/elements) are the gallery images and app icon for Elements Core. If you ever want to change/update them (eg. if or when you update the web UI), feel free to directly open a PR at [getumbrel/umbrel-apps-gallery](https://github.com/getumbrel/umbrel-apps-gallery). Keep up the amazing work!

**Comment by Impa10r** [comment]
Hello @tiero, thanks for putting it on Umbrel. I use it with PeerSwap now. I noticed there is no functionality to backup a wallet. Users will be freaked out when their Raspi fails (and they fail often). What is the best way to address this?

**Comment by SwapMarket** [comment]
@tiero Hi Marco. Are you looking to update this to v23.2.3?

**Comment by tiero** [comment]
> Hello @tiero, thanks for putting it on Umbrel. I use it with PeerSwap now. I noticed there is no functionality to backup a wallet. Users will be freaked out when their Raspi fails (and they fail often). What is the best way to address this?

Afaik there is no native support for bip39, how the backup would look like? Downloading the bag of keys? If is there a RPC for that can be simple as adding a button in that UI

**Comment by tiero** [comment]
> @tiero Hi Marco. Are you looking to update this to v23.2.3?

Yes will package a new docker image and ask for uodate here

**Comment by Impa10r** [comment]
> > Hello @tiero, thanks for putting it on Umbrel. I use it with PeerSwap now. I noticed there is no functionality to backup a wallet. Users will be freaked out when their Raspi fails (and they fail often). What is the best way to address this?
> 
> Afaik there is no native support for bip39, how the backup would look like? Downloading the bag of keys? If is there a RPC for that can be simple as adding a button in that UI

That's ok, I implemented the button in PeerSwap Web UI while ago

**Comment by emtreulapollaguera** [comment]
Hello @tiero ,

I have been using SideSwap connected to the Umbrel Elements Core and it has been functioning flawlessly until the recent updates from SideSwap.

I am curious if the docker needs an update now that a new Elements Core 23 version has been oficially released.

Are you planning to work on the Docker update?

Thank you!

**Comment by Impa10r** [comment]
> Are you planning to work on the Docker update?

I can do that when @tiero merges this PR https://github.com/vulpemventures/docker-elements/pull/10

**Comment by emtreulapollaguera** [comment]
Thank you @tiero and @Impa10r for pushing this forward,

> > merged! it should publish the new docker image soon
> 
> oops. docker build failed! buster-slim reached end of life. switching to bookworm: [vulpemventures/docker-elements#11](https://github.com/vulpemventures/docker-elements/pull/11)


What is currently the status?

**Comment by SwapMarket** [comment]
Docker image created. Intend to test and PR to Umbrel today. Then depends on how quickly they merge it.

**Pull request merged**
